--         TO_CHAR(TO_TIMESTAMP_NTZ(TO_NUMBER(TRY_PARSE_JSON(DATESCANNED):"$date"::STRING)/1000), 'MM-DD-YYYY HH24:MI:SS') as date_scanned,
--         BONUSPOINTSEARNED,
--         BONUSPOINTSEARNEDREASON,
--         TO_CHAR(TO_TIMESTAMP_NTZ(TO_NUMBER(TRY_PARSE_JSON(FINISHEDDATE):"$date"::STRING)/1000), 'MM-DD-YYYY HH24:MI:SS') as FINISHEDDATE,
--         TO_CHAR(TO_TIMESTAMP_NTZ(TO_NUMBER(TRY_PARSE_JSON(MODIFYDATE):"$date"::STRING)/1000), 'MM-DD-YYYY HH24:MI:SS') as MODIFYDATE,
--         TO_CHAR(TO_TIMESTAMP_NTZ(TO_NUMBER(TRY_PARSE_JSON(POINTSAWARDEDDATE):"$date"::STRING)/1000), 'MM-DD-YYYY HH24:MI:SS') as POINTSAWARDEDDATE,
--         POINTSEARNED,
--         TO_CHAR(TO_TIMESTAMP_NTZ(TO_NUMBER(TRY_PARSE_JSON(PURCHASEDATE):"$date"::STRING)/1000), 'MM-DD-YYYY HH24:MI:SS') as PURCHASEDATE,
--         PURCHASEDITEMCOUNT,
--         REWARDSRECEIPTSTATUS,
--         TOTALSPENT,
--         USERID

--     FROM source_data
-- )

-- SELECT
    
--     id as receipt_id,
--     created_date,
--     date_scanned,
--     BONUSPOINTSEARNED,
--     BONUSPOINTSEARNEDREASON,
--     FINISHEDDATE,
--     MODIFYDATE,
--     POINTSAWARDEDDATE,
--     POINTSEARNED,
--     PURCHASEDATE,
--     PURCHASEDITEMCOUNT,
--     REWARDSRECEIPTSTATUS,
--     TOTALSPENT,
--     USERID
   
-- FROM parsed_data


-- -- Good -- 

-- --- Now define the table name Items --

-- -- models/items.sql


-- models/stage_receipts.sql

{{ config(materialized='table') }}

WITH source_data AS (
    SELECT
        _ID AS id,
        DATESCANNED,
        FINISHEDDATE,
        MODIFYDATE,
        POINTSAWARDEDDATE,
        PURCHASEDATE,
        BONUSPOINTSEARNED,
        BONUSPOINTSEARNEDREASON,
        POINTSEARNED,
        PURCHASEDITEMCOUNT,
        REWARDSRECEIPTSTATUS,
        TOTALSPENT,
        USERID
    FROM {{ source("fetch_rewards","RECEIPTS") }}
)

SELECT
   PARSE_JSON(id):"$oid"::STRING AS id,
    TO_CHAR(TO_TIMESTAMP_NTZ(TO_NUMBER(PARSE_JSON(DATESCANNED):"$date")/1000), 'MM-DD-YYYY HH24:MI:SS') AS date_scanned,
    BONUSPOINTSEARNED,
    BONUSPOINTSEARNEDREASON,
    TO_CHAR(TO_TIMESTAMP_NTZ(TO_NUMBER(PARSE_JSON(FINISHEDDATE):"$date")/1000), 'MM-DD-YYYY HH24:MI:SS') AS finished_date,
    TO_CHAR(TO_TIMESTAMP_NTZ(TO_NUMBER(PARSE_JSON(MODIFYDATE):"$date")/1000), 'MM-DD-YYYY HH24:MI:SS') AS modify_date,
    TO_CHAR(TO_TIMESTAMP_NTZ(TO_NUMBER(PARSE_JSON(POINTSAWARDEDDATE):"$date")/1000), 'MM-DD-YYYY HH24:MI:SS') AS points_awarded_date,
    POINTSEARNED,
    TO_CHAR(TO_TIMESTAMP_NTZ(TO_NUMBER(PARSE_JSON(PURCHASEDATE):"$date")/1000), 'MM-DD-YYYY HH24:MI:SS') AS purchase_date,
    PURCHASEDITEMCOUNT,
    REWARDSRECEIPTSTATUS,
    TOTALSPENT,
    USERID
FROM source_data
